# Generated by Django 4.2.16 on 2025-05-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_alter_message_eml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='uri',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
